version: '3'
services:
  app:
    build:
      context: docker
      dockerfile: app/Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-net
  web:
    build:
      context: docker
      dockerfile: web/Dockerfile
    working_dir: /var/www
    ports:
      - 8088:80
    volumes:
      - .:/var/www
    networks:
      - app-net
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
networks:
    app-net:

volumes:
    exchange-rate-data:
    cache:
